version: "3.7"

services:
  #Composer Service
  composer:
    image: composer:1.10
    command: >
      sh -c "composer install && mkdir -p ./temp/cache/ && chmod -R 777 ./temp/ && chmod -R 777 ./log/ && cp ./app/config/local.neon.dev ./app/config/local.neon"
    volumes:
     - ../:/app

  #PHP Service
  php:
    image: php:7.2-fpm
    volumes:
     - ../:/var/www/sousedskapomoc.cz
    depends_on:
    - composer

  #Nginx Service
  web:
    build: .
    ports:
      - 80:80
    volumes:
     - ../:/var/www/sousedskapomoc.cz
     - ./nginx_conf/sousedskapomoc.cz.conf:/etc/nginx/conf.d/sousedskapomoc.cz.conf
    depends_on:
     - php
