version: "3.7"

services:
  #Composer Service
  composer:
    image: composer:1.10
    command: ["composer", "install"]
    volumes:
     - ../:/app

  #PHP Service
  php:
    build: .
    volumes:
     - ../:/var/www/sousedskapomoc.cz
    depends_on:
    - composer

  #Nginx Service
  web:
    image: nginx:latest
    command: >
      sh -c "if [ -f /etc/nginx/conf.d/default.conf ]; then rm /etc/nginx/conf.d/default.conf; fi&&
             mkdir -p /var/www/sousedskapomoc.cz/temp/cache/ &&
             chmod -R 777 /var/www/sousedskapomoc.cz/temp/ &&
             chmod -R 777 /var/www/sousedskapomoc.cz/log/ &&
             if [ -f ./app/config/local.neon.dev ]; then cp /var/www/sousedskapomoc.cz/app/config/local.neon.dev /var/www/sousedskapomoc.cz/app/config/local.neon; fi &&
             nginx -g 'daemon off;'"
    ports:
      - 80:80
    volumes:
     - ../:/var/www/sousedskapomoc.cz
     - ./nginx_conf/sousedskapomoc.cz.conf:/etc/nginx/conf.d/sousedskapomoc.cz.conf
    depends_on:
     - php
